spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uni_cms?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: unicms     # or 'root' if you prefer
    password: unicms_pw  # your password here
  jpa:
    hibernate:
      ddl-auto: update   # for development. Later we can switch to Flyway + validate
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate.format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
